modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
[[mods]]
modId="wkom"
version="pre-1.0.6"
displayName="WynnKunGz's Ores Mod"
credits="Thanks to PostChron, Bretzelfresser, Sir Squid, peewee, and Cy4."
authors="WynnKunGz"
description='''
Mod by WynnKunGz
Textures by WynnKunGz, PostChron, Sir Squid, peewee
Modding Tutorials by Cy4
Alloy Smelter by Bretzelfresser
'''

[[dependencies.wkom]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wkom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
